version: '3'
services: 
    api:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports: 
            - "8000:8000"
        volumes: 
            - ./backend/:/backend
    cli:
        build:
            context: .
            dockerfile: ./cli/Dockerfile
        volumes: 
            - ./cli/:/cli
        depends_on:
            - api

    streamlit:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        container_name: "streamlit-frontend"
        ports: 
            - "8501:8501"
        depends_on:
            - api
        volumes: 
            - ./frontend/:/frontend

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - streamlit
        ports:
            - "80:80"
    
